class McpBrainRouter < Formula
  include Language::Python::Virtualenv

  desc "MCP server routing delegated LLM work across a role-owned provider cascade"
  homepage "https://github.com/mohan-n-swamy/mcp-brain-router"
  url "https://github.com/mohan-n-swamy/mcp-brain-router/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "7fd451354e935bc11a206e8e83fec7a9b9cf2fb0b9f9b939ab342764861c9741"
  license "MIT"

  depends_on "python@3.12"

  # resource blocks below are auto-generated by `brew update-python-resources`

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "brain-router", shell_output("#{bin}/mcp-brain-router --help 2>&1", 0)
  end
end
